### ISSUE TITLE
Error while loading custom datapack

### ISSUE THREAD

**Issue by tdfischer** [Truly-Modular/Modular-Item-API#45]
**Describe the bug**
Using the material helper webtool, I created a .json file with the default settings and added it to my kubejs/data/miapi/materials/ folder, followed by /reload. In the console, I get:

```
[08Jun2024 10:34:47.128] [Server thread/INFO] [ModularItem API/]: MIAPI STARTED MATERIAL GENERATION
[08Jun2024 10:34:47.129] [Server thread/ERROR] [ModularItem API/]: Exception during reload
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
        at smartin.miapi.modules.material.JsonMaterial.<init>(JsonMaterial.java:41) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at smartin.miapi.modules.material.GeneratedMaterial.lambda$setup$0(GeneratedMaterial.java:77) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at smartin.miapi.datapack.ReloadEvents$ReloadEvent.lambda$fireEvent$0(ReloadEvents.java:254) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at smartin.miapi.datapack.ReloadEvents$ReloadEvent.fireEvent(ReloadEvents.java:252) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at smartin.miapi.forge.MiapiReloadListenerForge.apply(MiapiReloadListenerForge.java:59) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at smartin.miapi.forge.MiapiReloadListenerForge.m_5787_(MiapiReloadListenerForge.java:19) ~[Truly-Modular-miapi-forge-1.1.23-1.20.1.jar%23570!/:?]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
--
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23591!/:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[08Jun2024 10:34:47.180] [Server thread/WARN] [ModularItem API/]: ItemModule is null?
[08Jun2024 10:34:47.187] [Server thread/INFO] [ModularItem API/]: Loaded 1 Injectors/Property Substitutors
[08Jun2024 10:34:47.187] [Server thread/INFO] [ModularItem API/]: Loaded 152 Modules
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Loaded 69 Synergies
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Loaded 115 Materials
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Found 85 Enchantments
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Loaded 58 Modular Converters
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Loaded 995 Skins
[08Jun2024 10:34:47.188] [Server thread/INFO] [ModularItem API/]: Server load took 10153.844552999999 ms
```

And no extra new materials ;(

Looking at the code referenced in the stacktrace, it seems like it is always being passed an empty JSON object and unsurprisingly fails.

**To Reproduce**
1. Go to https://truly-modular.github.io/Material-Helper/
2. Change nothing, download the json as-is
3. Install in a datapack

**Expected behavior**
New materials, no errors

**Screenshots**
N/A

**Minecraft and Mod Version:**
Minecraft: 1.20
Forge/Fabric: 47.3.0
Miapi: v1.1.23-1.20.1

**Comment by Smartin-b** [comment]
can you send me the datapack you made?
because you shouldnt be able to "change nothing, download the json as-is" from the webhelper, it should require you to set a item and name at minimum

**Comment by Smartin-b** [comment]
also, can you make sure the datapack is loaded correctly by using /datapack list ingame and see if the website made one appears in the list?

**Comment by Smartin-b** [comment]
since this erro was unrelated cause by a feature called NBT materials (not json materials) and you havent responded im asuming the issue was resolved, if you still having trouble either join the discord or re-open this issue
